# Generated by Django 4.0.2 on 2022-05-04 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Start date')),
                ('feedback', models.TextField(blank=True, max_length=500, null=True, verbose_name='Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='UserStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_description', models.CharField(max_length=50, verbose_name='User Status')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHoursModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Change description')),
                ('rate_of_pay', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Wage rate')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, verbose_name='PESEL')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('phone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('post_code', models.CharField(max_length=6, verbose_name='Post Code')),
                ('house_number', models.CharField(max_length=20, verbose_name='House Number')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('user_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_state', to='hrms.userstatemodel', verbose_name='Stan użytkownika')),
                ('user_work_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_hours', to='hrms.workhoursmodel', verbose_name='Godziny pracy')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=200, verbose_name='rfid')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_access', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=300, verbose_name='Client name')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number', models.IntegerField(verbose_name='Project number')),
                ('number_2', models.IntegerField(verbose_name='Project number 2')),
                ('project_type', models.CharField(max_length=50, verbose_name='Project type')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('contact', models.CharField(max_length=500, verbose_name='Contact')),
                ('comments', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('id_employee', models.ManyToManyField(related_name='project_employee_user', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('id_project_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is completed')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is approved')),
                ('approver_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Approving person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_user', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Entrance Time')),
                ('end_date', models.DateField(verbose_name='Finish Time')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approver_user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Approving person')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_reason', to='hrms.entranceexitreason', verbose_name='Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_user', to=settings.AUTH_USER_MODEL, verbose_name='attendee')),
            ],
        ),
    ]
